하루스터디의 Github Action을 이용한 CI 구축기
haru-study/haru-study.github.io pull request #2
Opened 2023-07-17 03:54 UTC by aak2075

하루스터디의 Github Action을 이용한 CI 구축기입니다. 소나큐브도 추가하게 되면 소나큐브에 대한 글도 새로 쓰겠습니다
이후에 CD구축기도 올릴 예정입니다.

2023-07-17 04:12 UTC, yeopto approved these changes
Look so good

2023-07-17 04:14 UTC, woosung1223 reviewed
고생했습니다잉

2023-07-17 04:14 UTC, woosung1223 approved these changes

2023-07-17 15:09 UTC, yeopto requested changes
마코~ CI 내용에 대해 백과 프론트 합쳐봤어요. 한번 검토해봐요~

2023-07-17 15:09 UTC, yeopto commented on _posts/2023-07-17-하루스터디의 Github Action을 이용한 CI 구축기.md
> +  - BackEnd
```suggestion
  - Infra
```

2023-07-17 15:09 UTC, yeopto commented on _posts/2023-07-17-하루스터디의 Github Action을 이용한 CI 구축기.md
> +> 이 글은 백엔드 크루 마코가 작성했습니다.
```suggestion
> 이 글은 백엔드 크루 마코와 프론트엔드 크루 엽토가 작성했습니다.
```

2023-07-17 15:09 UTC, yeopto commented on _posts/2023-07-17-하루스터디의 Github Action을 이용한 CI 구축기.md
> +하루스터디 백엔드의 CI 도입 배경과 Github Action 선택 과정, 그리고 어떻게 CI를 구축했는지에 대해서 알아보겠습니다.
```suggestion
하루스터디 CI 도입 배경과 Github Action 선택 과정, 그리고 어떻게 CI를 구축했는지에 대해서 알아보겠습니다.
```

2023-07-17 15:09 UTC, yeopto commented on _posts/2023-07-17-하루스터디의 Github Action을 이용한 CI 구축기.md
> +Pull Request를 제출할 때 마다 빌드와 테스트를 돌리는 것은 꽤 많은 컴퓨팅 파워를 소모하고 이는 빌드와 테스트만을 위한 서버를 필요로 하게 됩니다.
```suggestion
위에서 설명한 과정(PR-> build -> test)들을 자동화 하기 위해서는 빌드와 테스트를 확인하는 전용 서버를 필요로 하게 됩니다. Pull Request를 제출할 때 마다 위 과정들이 진행되는 것은 꽤나 많은 컴퓨팅 파워를 소모하게 되는데요.
```

2023-07-17 15:09 UTC, yeopto commented on _posts/2023-07-17-하루스터디의 Github Action을 이용한 CI 구축기.md
> +하루스터디는 RAM 2GB 사양의 EC2 인스턴스를 보유하고 있습니다. RAM 2GB로 빌드와 테스트를 모두 수행하기에는 조금 불안정한 사양입니다.
```suggestion
하루스터디는 RAM 2GB 사양의 EC2 인스턴스를 3대를 보유하고 있습니다. 한 대는 DB 전용 서버, 한 대는 배포 서버, 마지막으로 남은 한 대는 배포 자동화 서버로 사용하기로 했습니다. 물론 배포 자동화 서버에서 CI 자동화를 돌릴 수도 있겠지만, RAM 2GB로 빌드와 테스트를 수행하고 배포 자동화 까지 하는 것은 조금 불안정한 사양이라고 생각했습니다.
```

2023-07-17 15:09 UTC, yeopto commented on _posts/2023-07-17-하루스터디의 Github Action을 이용한 CI 구축기.md
> +Github-Action은 github에서 제공하는 클라우드 환경에서 실행되는 github-hosted-runner 를 사용하여 CI를 수행할 수 있습니다.
```suggestion
서버 자원이 한정적이라 CI를 외부에서 수행할 수 있는 방법을 찾던 중, Github-Action을 알게되었습니다. Github-Action은 github에서 제공하는 클라우드 환경에서 실행되는 github-hosted-runner 를 사용하여 CI를 수행할 수 있었습니다.
```

2023-07-17 15:09 UTC, yeopto commented on _posts/2023-07-17-하루스터디의 Github Action을 이용한 CI 구축기.md
> +github-hosted-runner를 사용하기 위해 제공되는 클라우드의 성능은 최소 RAM 7GB 이상이기 때문에 훨씬 안정적인 환경에서 빌드와 테스트를 수행함은 물론 서버 자원도 아낄 수 있습니다.
```suggestion
github-hosted-runner를 사용하기 위해 제공되는 클라우드의 성능은 최소 RAM 7GB 이상이기 때문에 훨씬 안정적인 환경에서 빌드와 테스트를 수행함은 물론 서버 자원도 아낄 수 있어서 저희의 문제를 해결할 수 있었습니다.
```

2023-07-17 15:09 UTC, yeopto commented on _posts/2023-07-17-하루스터디의 Github Action을 이용한 CI 구축기.md
> +추후에 CI과정에 정적 코드 분석을 해주는 소나큐브도 도입할 예정인데요, 이 결과를 Pull Request에 댓글로 달아준다면 팀원들이 확인하기 좋겠죠?
```suggestion
추후에 CI과정에 정적 코드 분석을 해주는 `SonarQube`와 프론트엔드 성능 테스트 도구인 `Lighthouse`를 도입할 예정인데요, 이 결과를 Pull Request에 댓글로 달아준다면 팀원들이 확인하기 좋겠죠?
```

2023-07-17 15:09 UTC, yeopto commented on _posts/2023-07-17-하루스터디의 Github Action을 이용한 CI 구축기.md
> +트리거는 develop 브랜치에 Pull Request가 발생했을 때, 변경됐을 때, reopened 됐을 때 수행됩니다.
```suggestion
먼저, 하나의 레포지토리에서 프론트엔드와 백엔드 코드가 관리되기 때문에 script를 각각 분리해주었고, 트리거는 develop 브랜치에 Pull Request가 발생했을 때, 변경됐을 때, reopened 됐을 때 각 script가 수행됩니다.
```

2023-07-17 15:09 UTC, yeopto commented on _posts/2023-07-17-하루스터디의 Github Action을 이용한 CI 구축기.md
> +그 중에서 백엔드 코드의 기능 추가나 리팩토링에 대해서만 빌드와 테스트를 진행하면 되기 때문에 Pull Request의 라벨 중 BE와 feautre 또는 BE와 refactor가 붙어있는 경우에만 실행하도록 설계했습니다.
```suggestion
그 중에서 기능 추가나 리팩토링에 대해서만 빌드와 테스트를 진행하면 되기 때문에 Pull Request의 라벨 중 BE와 feature 또는 BE와 refactor가 붙어있는 경우 그리고 FE와 feature 또는 FE와 refactor가 붙어있는 경우에만 실행하도록 설계했습니다. FE와 BE에 대해서는 script를 분리해줬기때문에 CI 실행시 각 분야별 script만 실행됩니다. 
```

2023-07-17 15:09 UTC, yeopto commented on _posts/2023-07-17-하루스터디의 Github Action을 이용한 CI 구축기.md
> +
```suggestion
**백엔드 step은 다음과 같습니다.**
```

2023-07-17 15:09 UTC, yeopto commented on _posts/2023-07-17-하루스터디의 Github Action을 이용한 CI 구축기.md
> +
```suggestion
**프론트엔드 step은 다음과 같습니다.**

1. 소스 코드를 클론합니다.
2. 빌드 환경을 node 18버전으로 설정합니다.
3. 의존성을 clean install 합니다.
4. 테스트 및 빌드를 진행합니다.
5. 결과를 하루스터디의 슬랙으로 알림을 보내줍니다.
```

2023-07-17 15:09 UTC, yeopto commented on _posts/2023-07-17-하루스터디의 Github Action을 이용한 CI 구축기.md
> +작성한 workflow는 다음과 같습니다.
```suggestion
각 분야별로 작성한 workflow는 다음과 같습니다.
```

2023-07-17 15:09 UTC, yeopto commented on _posts/2023-07-17-하루스터디의 Github Action을 이용한 CI 구축기.md
> +
```suggestion
```yml
name: frontend-build-test

on:
  pull_request:
    branches:
      - develop

    types: [opened, synchronize, reopened]

defaults:
  run:
    working-directory: ./frontend

jobs:
  build:
    # label이 FE와 feature일때 혹은 FE와 refactor일때 워크플로우를 실행시킨다.
    if: |
      (contains(github.event.pull_request.labels.*.id, 5681130676) && 
      contains(github.event.pull_request.labels.*.id, 5681142648)) ||
      (contains(github.event.pull_request.labels.*.id, 5681130676) && 
      contains(github.event.pull_request.labels.*.id, 5681143873)) 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Test & Build
        run: yarn build
      
      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Github Action # default: 8398a7@action-slack
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always()
```
```

2023-07-17 15:09 UTC, yeopto commented on _posts/2023-07-17-하루스터디의 Github Action을 이용한 CI 구축기.md
> +해당 PR은 라벨 중 BE,feature 또는 BE,refactor 가 붙어있지 않기 때문에 workflow가 Skipped되어 체크가 패스된 것을 확인할 수 있습니다.
```suggestion
해당 PR은 라벨 중 BE,feature 또는 BE,refactor 그리고 FE,feature 또는 FE,refactor가 붙어있지 않기 때문에 workflow가 Skipped되어 체크가 패스된 것을 확인할 수 있습니다.
```

2023-07-17 15:09 UTC, yeopto commented on _posts/2023-07-17-하루스터디의 Github Action을 이용한 CI 구축기.md
> +하루스터디 백엔드의 CI 도입 배경과 Github Action 선택 과정, 그리고 어떻게 CI를 구축했는지 알아봤습니다.
```suggestion
하루스터디 CI 도입 배경과 Github Action 선택 과정, 그리고 어떻게 CI를 구축했는지 알아봤습니다.
```

2023-07-17 15:09 UTC, yeopto commented on _posts/2023-07-17-하루스터디의 Github Action을 이용한 CI 구축기.md
> +다음으로는 정적 코드 분석을 위한 소나큐브를 CI과정에 도입하고 배포까지 자동화하는 CD도 구축할 예정이니 다음 글을 기다려주세요. 감사합니다.
```suggestion
다음으로는 정적 코드 분석을 위한 SonarQube 그리고 프론트엔드 성능 테스트를 위한 Lighthouse를 CI과정에 도입하고, 배포까지 자동화하는 CD도 구축할 예정이니 다음 글을 기다려주세요. 감사합니다.
```

2023-07-18 16:17 UTC, yeopto approved these changes
코멘트 딱 하나 남겼습니다! 수고했어요 마코!

2023-07-18 16:17 UTC, yeopto commented on _posts/2023-07-17-하루스터디의 Github Action을 이용한 CI 구축기.md
> +위에서 설명한 과정(PR-> build -> test)들을 자동화 하기 위해서는 빌드와 테스트를 확인하는 전용 서버를 필요로 하게 되는데요, Pull Request를 제출할 때 마다 위 과정들이 진행되는 것은 꽤나 많은 컴퓨팅 파워를 소모하게 되는데요.
요기 되는데요 두번이네용!

2023-07-20 09:03 UTC, MoonJeWoong approved these changes
CI 정리하시느라 고생하셨어요! CD도 얼른 정리 부탁드려요~

2023-07-20 09:03 UTC, merged